/**
 * Generated by the Croct CLI.
 *
 * Any manual changes will be overwritten.
 *
 * To regenerate, run `croct update`.
 */

type Def$0db98ba2 = {
  /**
   * Hero
   */
  'hero': Def$770140b4,
  /**
   * Highlights
   */
  'highlights': Def$48850506,
};

type Def$0147aaec = string;

/**
 * Hero section with card
 * 
 * A big section featured at the top of a page.
 */
type Def$770140b4 = {
  /**
   * Tag
   */
  'tag'?: string,
  /**
   * Card
   */
  'card': {
    /**
     * Color
     */
    'color'?: string,
    /**
     * Title
     */
    'title'?: string,
    /**
     * CTA label
     */
    'ctaLabel': string,
    /**
     * Full price
     */
    'fullPrice': {
      /**
       * Label
       */
      'label'?: string,
      /**
       * Value
       */
      'value': number,
    },
    /**
     * Alternate price
     */
    'alternatePrice': {
      /**
       * Label
       */
      'label': string,
      /**
       * Value
       */
      'value': number,
      /**
       * Installments
       */
      'installments': number,
    },
  },
  /**
   * Image
   * 
   * The image to display alongside the heading and tagline.
   */
  'image': Def$0147aaec,
  /**
   * Heading
   * 
   * The main heading of the page.
   */
  'heading': string,
  /**
   * Tagline
   * 
   * The tagline of the page.
   */
  'tagline': string,
  /**
   * Pre-title
   */
  'preTitle'?: string,
};

/**
 * Items with image and text
 * 
 * A list of ordered items.
 */
type Def$48850506 = {
  /**
   * Items
   */
  'items': Array<{
    /**
     * Text
     * 
     * The title or description of the item.
     */
    'text': string,
    /**
     * Image
     * 
     * The image of the item.
     */
    'image': Def$0147aaec,
  }>,
  /**
   * Title
   */
  'title'?: string,
};

type Def$6365e50d = {
  /**
   * Imagem
   */
  'imagem': Def$0147aaec,
  /**
   * Título
   */
  'titulo': string,
  /**
   * ctaLabel
   */
  'ctalabel': string,
  /**
   * Descricao
   */
  'descricao': string,
};

declare module '@croct/plug/slot' {
  type LpCapacitacaoParaAplicadoresAbaEadV2 = Def$0db98ba2 & {'_component': 'lp-component@1' | null};
  type LpTesteV1 = Def$6365e50d & {'_component': 'lp-hero@1' | null};
  
  export interface VersionedSlotMap {
    'lp-capacitacao-para-aplicadores-aba-ead': {
      latest: LpCapacitacaoParaAplicadoresAbaEadV2,
      '2': LpCapacitacaoParaAplicadoresAbaEadV2,
    };

    'lp-teste': {
      latest: LpTesteV1,
      '1': LpTesteV1,
    };
  }
}

export {};