/**
 * Generated by the Croct CLI.
 *
 * Any manual changes will be overwritten.
 *
 * To regenerate, run `croct update`.
 */

/**
 * Next.js 15 starter page
 * 
 * The structure for Next.js 15 starter pages.
 */
type Def$7f15019b = {
  /**
   * Instructions
   * 
   * The steps to help users get started.
   */
  'instructions': Array<string>,
  /**
   * Primary button
   * 
   * The primary call-to-action button.
   */
  'primaryButton': {
    /**
     * URL
     * 
     * The link the button points to.
     */
    'url': string,
    /**
     * Label
     * 
     * The label shown on the button.
     */
    'label': string,
  },
  /**
   * Secondary button
   * 
   * The secondary call-to-action button.
   */
  'secondaryButton': {
    /**
     * URL
     * 
     * The link the button points to.
     */
    'url': string,
    /**
     * Label
     * 
     * The label shown on the button.
     */
    'label': string,
  },
};

/**
 * Sobre empresa page
 * 
 * The structure for about company pages.
 */
type Def$sobre = {
  'titulo': string,
  'subtitulo': string,
  'descricao': string,
  'features': Array<{
    'titulo': string,
    'descricao': string,
    'icone': string,
  }>,
  'chamadaAcao': {
    'titulo': string,
    'botao': {
      'texto': string,
      'url': string,
    },
  },
};

declare module '@croct/plug/slot' {
  type Next15HomepageV2 = Def$7f15019b & {'_component': 'next15-starter-page@3' | null};
  type SobreEmpresaV1 = Def$sobre & {'_component': 'sobre-empresa-page@1' | null};
  
  export interface VersionedSlotMap {
    'next15-homepage': {
      latest: Next15HomepageV2,
      '2': Next15HomepageV2,
    };
    'sobre-empresa': {
      latest: SobreEmpresaV1,
      '1': SobreEmpresaV1,
    };
  }
}

export {};