/**
 * Generated by the Croct CLI.
 *
 * Any manual changes will be overwritten.
 *
 * To regenerate, run `croct update`.
 */

type Def$e5ac4cc5 = {
  /**
   * Instructions
   * 
   * The steps to help users get started.
   */
  'instructions': Array<string>,
  /**
   * Primary button
   * 
   * The primary call-to-action button.
   */
  'primaryButton': {
    /**
     * URL
     * 
     * The link the button points to.
     */
    'url': string,
    /**
     * Label
     * 
     * The label shown on the button.
     */
    'label': string,
  },
  /**
   * Secondary button
   * 
   * The secondary call-to-action button.
   */
  'secondaryButton': {
    /**
     * URL
     * 
     * The link the button points to.
     */
    'url': string,
    /**
     * Label
     * 
     * The label shown on the button.
     */
    'label': string,
  },
};

declare module '@croct/plug/slot' {
  type Next15HomepageV1 = Def$e5ac4cc5 & {'_component': 'next15-starter-page@1' | null};
  
  export interface VersionedSlotMap {
    'next15-homepage': {
      latest: Next15HomepageV1,
      '1': Next15HomepageV1,
    };
  }
}

export {};